<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Profile <?=$this->e($title)?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Personal Website - Mehmet Gökce" />
    <meta name="author" content="Mehmet Gökce" />



    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="css/style.css">

    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135909508-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-135909508-1');
    </script>


</head>

<body>

<div class="fh5co-loader"></div>

<div id="page">

    <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner" style="background-image:url(images/programming1.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t js-fullheight">
                        <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
                            <div class="profile-thumb" style="background: url(images/memyselfandi.jpg);"></div>
                            <h1><span>Mehmet Gökce</span></h1>
                            <h2><span>Software Developer</span></h2>
                            <h3><span>Data Analysis, ECommerce, PIM, CRM, CMS</span></h3>
                            <p>
                            <ul class="fh5co-social-icons">
                                <li><a href="https://twitter.com/mehmetgoekce"><i class="icon-twitter2"></i></a></li>
                                <li><a href="https://de.linkedin.com/in/mehmetgoekce"><i class="icon-linkedin2"></i></a></li>
                                <li><a href="https://github.com/MehmetGoekce"><i class="icon-github2"></i></a></li>
                            </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <?php echo $this->section('content')?>
    <div id="fh5co-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>&copy; 2019 Mehmet Gökce</p>
                </div>
            </div>
        </div>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up22"></i></a>
    </div>

    <!-- jQuery -->
    <script src="js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="js/jquery.waypoints.min.js"></script>
    <!-- Stellar Parallax -->
    <script src="js/jquery.stellar.min.js"></script>
    <!-- Easy PieChart -->
    <script src="js/jquery.easypiechart.min.js"></script>


    <!-- Main -->
    <script src="js/main.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->



</body>
</html>